# Generated by Django 6.1.1 on 2026-09-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cents', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_accounts',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('mpesa_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='meals.mealaccount')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_meals', models.IntegerField()),
                ('predicted_cost_cents', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='meals.school')),
            ],
            options={
                'db_table': 'demand_forecasts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('kitchen', 'Kitchen Staff'), ('bursar', 'Bursar'), ('admin', 'School Admin')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='meals.school')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MealDistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meals_served', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_events', to='meals.mealaccount')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'kitchen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_distributions', to='meals.user')),
            ],
            options={
                'db_table': 'meal_distribution_events',
            },
        ),
        migrations.AddField(
            model_name='mealaccount',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='meal_account', to='meals.user'),
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flag', to='meals.paymenttransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'bursar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to='meals.user')),
            ],
            options={
                'db_table': 'anomaly_flags',
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandforecast',
            unique_together={('school', 'forecast_date')},
        ),
        migrations.AddIndex(
            model_name='mealdistributionevent',
            index=models.Index(fields=['meal_date'], name='meal_distri_meal_da_104072_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['anomaly_score'], name='anomaly_fla_anomaly_75b327_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyflag',
            index=models.Index(fields=['reviewed'], name='anomaly_fla_reviewe_d88d1c_idx'),
        ),
    ]
