# Generated by Django 6.1.1 on 2026-09-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_termschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealaccount',
            name='credit_limit_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealaccount',
            name='guardians',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'parent'}, related_name='linked_meal_accounts', to='meals.user'),
        ),
        migrations.AddField(
            model_name='mealdistributionevent',
            name='amount_cents',
            field=models.IntegerField(default=5000),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_cents', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='meals.school')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mealdistributionevent',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='distribution_events', to='meals.menuitem'),
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount_cents', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('meal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='meals.mealaccount')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='meals.user')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credit_requests', to='meals.user')),
            ],
            options={
                'db_table': 'credit_requests',
                'indexes': [models.Index(fields=['status'], name='credit_requ_status_f2488a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('balance', 'Balance / Payment'), ('meal_quality', 'Meal Quality'), ('technical', 'App / Technical'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('meal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='meals.mealaccount')),
                ('raised_by', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='raised_issues', to='meals.user')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to='meals.user')),
            ],
            options={
                'db_table': 'support_issues',
                'indexes': [models.Index(fields=['status'], name='support_iss_status_cdc6b3_idx')],
            },
        ),
    ]
