# Generated by Django 6.1.1 on 2026-09-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealaccount_credit_limit_cents_mealaccount_guardians_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='combos', to='meals.menuitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_combos', to='meals.school')),
            ],
            options={
                'db_table': 'meal_combos',
                'ordering': ['name'],
            },
        ),
    ]
