# Generated by Django 6.1.1 on 2026-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_mealcombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('kitchen', 'Kitchen Staff'), ('bursar', 'Bursar'), ('admin', 'School Admin'), ('superadmin', 'Super Admin')], max_length=20),
        ),
    ]
