# Generated by Django 6.1.1 on 2026-09-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Technical / Platform Bug'), ('billing', 'Billing & Payments'), ('feature_request', 'Feature Request'), ('data', 'Data / Reporting Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='raised_admin_issues', to='meals.user')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'superadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_admin_issues', to='meals.user')),
            ],
            options={
                'db_table': 'admin_issues',
                'indexes': [models.Index(fields=['status'], name='admin_issue_status_ad2a95_idx')],
            },
        ),
    ]
