# Generated by Django 6.1.1 on 2026-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_mealaccount_qr_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealdistributionevent',
            index=models.Index(fields=['meal_account', 'meal_date'], name='meal_distri_meal_ac_26a62d_idx'),
        ),
    ]
